version: '3.9'
networks:
  default:
    driver: bridge
services:
  # InfluxDB - Time series database for storing radio metrics
  influxdb:
    build:
      context: .
    image: influxdb:2.7.4
    env_file:
      - ./influxdb/influxdb.env
    container_name: influxdb
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - '8086:8086'
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
