/*
This file contains all of the descriptions used by FLA when showing the different types of messages which can be displayed.
*/

const mavlinkMessageDescriptions = {
  SYS_STATUS: "The general system state.",
  SYSTEM_TIME:
    "The system time is the time of the master clock, typically the computer clock of the main onboard computer.",
  GPS_RAW_INT:
    "The global position, as returned by the Global Positioning System (GPS). This is NOT the global position estimate of the system, but rather a RAW sensor value.",
  GPS_STATUS:
    "The positioning status, as reported by GPS. This message is intended to display status information about each satellite visible to the receiver.",
  SCALED_IMU:
    "The RAW IMU readings for the usual 9DOF sensor setup. This message should contain the scaled values to the described units",
  RAW_IMU:
    "The RAW IMU readings for a 9DOF sensor, which is identified by the id (default IMU1). This message should always contain the true raw values without any scaling to allow data capture and system debugging.",
  RAW_PRESSURE:
    "The RAW pressure readings for the typical setup of one absolute pressure and one differential pressure sensor. The sensor values should be the raw, UNSCALED ADC values.",
  SCALED_PRESSURE:
    "The pressure readings for the typical setup of one absolute and differential pressure sensor. The units are as specified in each field.",
  ATTITUDE:
    "The attitude in the aeronautical frame (right-handed, Z-down, Y-right, X-front, ZYX, intrinsic).",
  ATTITUDE_QUATERNION:
    "The attitude in the aeronautical frame (right-handed, Z-down, X-front, Y-right), expressed as quaternion. Quaternion order is w, x, y, z and a zero rotation would be expressed as (1 0 0 0).",
  LOCAL_POSITION_NED:
    "The filtered local position (e.g. fused computer vision and accelerometers). Coordinate frame is right-handed, Z-axis down (aeronautical frame, NED / north-east-down convention)",
  GLOBAL_POSITION_INT:
    "The filtered global position (e.g. fused GPS and accelerometers). The position is in GPS-frame (right-handed, Z-up). It is designed as scaled integer message since the resolution of float is not sufficient.",
  RC_CHANNELS_SCALED:
    "The scaled values of the RC channels received: (-100%) -10000, (0%) 0, (100%) 10000. Channels that are inactive should be set to INT16_MAX.",
  RC_CHANNELS_RAW:
    "The RAW values of the RC channels received. The standard PPM modulation is as follows: 1000 microseconds: 0%, 2000 microseconds: 100%. A value of UINT16_MAX implies the channel is unused. Individual receivers/transmitters might violate this specification.",
  SERVO_OUTPUT_RAW:
    "Superseded by ACTUATOR_OUTPUT_STATUS. The RAW values of the servo outputs (for RC input from the remote, use the RC_CHANNELS messages). The standard PPM modulation is as follows: 1000 microseconds: 0%, 2000 microseconds: 100%.",
  NAV_CONTROLLER_OUTPUT: "The state of the navigation and position controller.",
  RC_CHANNELS:
    "The PPM values of the RC channels received. The standard PPM modulation is as follows: 1000 microseconds: 0%, 2000 microseconds: 100%. A value of UINT16_MAX implies the channel is unused. Individual receivers/transmitters might violate this specification.",
  VFR_HUD: "Metrics typically displayed on a HUD for fixed wing aircraft.",
  RADIO_STATUS: "Status generated by radio and injected into MAVLink stream.",
  POWER_STATUS: "Power supply status.",
  DISTANCE_SENSOR: "Distance sensor information for an onboard rangefinder.",
  BATTERY_STATUS:
    "Battery information. Updates GCS with flight controller battery status.",
  VIBRATION: "Vibration levels and accelerometer clipping.",
}

export const logMessageDescriptions = {
  ...mavlinkMessageDescriptions,
}
