/*
This file contains all of the descriptions used by FLA when showing the different types of messages which can be displayed.
*/

// https://ardupilot.org/copter/docs/logmessages.html#logmessages

const dataflashLogMessageDescriptions = {
  ACC: "IMU accelerometer data",
  ADSB: "Automatic Dependent Serveillance - Broadcast detected vehicle information",
  AHR2: "Backup AHRS data",
  AIS1: "Contents of 'position report' AIS message, see: https://gpsd.gitlab.io/gpsd/AIVDM.html#_types_1_2_and_3_position_report_class_a",
  AIS4: "Contents of 'Base Station Report' AIS message, see: https://gpsd.gitlab.io/gpsd/AIVDM.html#_type_4_base_station_report",
  AIS5: "Contents of 'static and voyage related data' AIS message, see: https://gpsd.gitlab.io/gpsd/AIVDM.html#_type_5_static_and_voyage_related_data",
  AISR: "Raw AIS AVDIM messages contents, see: https://gpsd.gitlab.io/gpsd/AIVDM.html#_aivdmaivdo_sentence_layer",
  AOA: "Angle of attack and Side Slip Angle values",
  ARM: "Arming status changes",
  AROT: "Helicopter AutoRotation information",
  ARSP: "Airspeed sensor data",
  ASM1: "AirSim simulation data",
  ASM2: "More AirSim simulation data",
  ATDE: "AutoTune data packet",
  ATDH: "Heli AutoTune data packet",
  ATNH: "Heli AutoTune",
  ATSC: "Scale factors for attitude controller",
  ATSH: "Heli AutoTune Sweep packet",
  ATT: "Canonical vehicle attitude",
  ATUN: "Copter/QuadPlane AutoTune",
  AUXF: "Auxiliary function invocation information",
  BARD: "Barometer dynamic data",
  BARO: "Gathered Barometer data",
  BAT: "Gathered battery data",
  BCL: "Battery cell voltage information",
  BCL2: "Battery cell voltage information",
  BCN: "Beacon information",
  CAM: "Camera shutter information",
  CAND: "Info from GetNodeInfo request",
  CMD: "Executed mission command information",
  CSRV: "Servo feedback data",
  CTRL: "Attitude Control oscillation monitor diagnostics",
  CTUN: "Control Tuning information",
  D16: "Generic 16-bit-signed-integer storage",
  D32: "Generic 32-bit-signed-integer storage",
  DFLT: "Generic float storage",
  DMS: "DataFlash-Over-MAVLink statistics",
  DSF: "Onboard logging statistics",
  DSTL: "Deepstall Landing data",
  DU16: "Generic 16-bit-unsigned-integer storage",
  DU32: "Generic 32-bit-unsigned-integer storage",
  EAH3: "External AHRS data",
  EAHR: "External AHRS data",
  ECYL: "EFI per-cylinder information",
  EFI: "Electronic Fuel Injection system data",
  EFI2: "Electronic Fuel Injection system data - redux",
  EFIS: "Electronic Fuel Injection data - Hirth specific Status information",
  ERR: "Specifically coded error messages",
  ESC1: "Feedback received from ESC instance 1",
  ESC2: "Feedback received from ESC instance 2",
  ESC3: "Feedback received from ESC instance 3",
  ESC4: "Feedback received from ESC instance 4",
  ESC5: "Feedback received from ESC instance 5",
  ESC6: "Feedback received from ESC instance 6",
  ESC7: "Feedback received from ESC instance 7",
  ESC8: "Feedback received from ESC instance 8",
  ESC9: "Feedback received from ESC instance 9",
  ESC10: "Feedback received from ESC instance 10",
  ESC11: "Feedback received from ESC instance 11",
  ESC12: "Feedback received from ESC instance 12",
  EV: "Specifically coded event messages",
  FCN: "Filter Center Message - per motor",
  FCNS: "Filter Center Message",
  FHLD: "FlowHold mode messages",
  FHXY: "Height estimation using optical flow sensor",
  FILE: "File data",
  FMT: "Message defining the format of messages in this file",
  FMTU: "Message defining units and multipliers used for fields of other messages",
  FNCE: "currently loaded Geo Fence points",
  FOLL: "Follow library diagnostic data",
  FTN: "Filter Tuning Message - per motor",
  FTN1: "FFT Filter Tuning",
  FTN2: "FFT Noise Frequency Peak",
  FTNS: "Filter Tuning Message",
  GMB1: "Solo Gimbal measurements",
  GMB2: "Solo Gimbal estimation and demands",
  GPA: "GPS accuracy information",
  GPS: "Information received from GNSS systems attached to the autopilot",
  GPYW: "GPS Yaw",
  GRAW: "Raw uBlox data",
  GRXH: "Raw uBlox data - header",
  GRXS: "Raw uBlox data - space-vehicle data",
  GUIA: "Guided mode attitude target information",
  GUIP: "Guided mode position target information",
  GYR: "IMU gyroscope data",
  HEAT: "IMU Heater data",
  HELI: "Helicopter related messages",
  HYGR: "Hygrometer data",
  ICMB: "ICM20789 diagnostics",
  ILB1: "InertialLabs AHRS data1",
  ILB2: "InertialLabs AHRS data3",
  IMU: "Inertial Measurement Unit data",
  IOMC: "IOMCU diagnostic information",
  JSN1: "Log data received from JSON simulator",
  JSN2: "Log data received from JSON simulator",
  LAND: "Slope Landing data",
  LGR: "Landing gear information",
  MAG: "Information received from compasses",
  MAGH: "Magnetometer high resolution data",
  MAV: "GCS MAVLink link statistics",
  MAVC: "MAVLink command we have just executed",
  MCU: "MCU voltage and temprature monitering",
  MMO: "MMC3416 compass data",
  MNT: "Mount's desired and actual roll, pitch and yaw angles",
  MODE: "vehicle control mode information",
  MON: "Main loop performance monitoring message.",
  MOTB: "Motor mixer information",
  MSG: "Textual messages",
  MULT: "Message mapping from single character to numeric multiplier",
  NKF0: "EKF2 beacon sensor diagnostics",
  NKF1: "EKF2 estimator outputs",
  NKF2: "EKF2 estimator secondary outputs",
  NKF3: "EKF2 innovations",
  NKF4: "EKF2 variances SV, SP, SH and SM are probably best described as 'Squared Innovation Test Ratios' where values <1 tells us the measurement was accepted and >1 tells us it was rejected.",
  NKF5: "EKF2 Sensor innovations (primary core) and general dumping ground",
  NKQ: "EKF2 quaternion defining the rotation from NED to XYZ (autopilot) axes",
  NKT: "EKF2 timing information",
  NKY0: "EKF Yaw Estimator States",
  NKY1: "EKF Yaw Estimator Innovations",
  OABR: "Object avoidance (Bendy Ruler) diagnostics",
  OADJ: "Object avoidance (Dijkstra) diagnostics",
  OAVG: "Object avoidance path planning visgraph points",
  OF: "Optical flow sensor data",
  OFCA: "Optical Flow Calibration sample",
  ORGN: "Vehicle navigation origin or other notable position",
  PARM: "parameter value",
  PIDA: "Proportional/Integral/Derivative gain values for vertical acceleration",
  PIDE: "Proportional/Integral/Derivative gain values for East/West velocity",
  PIDN: "Proportional/Integral/Derivative gain values for North/South velocity",
  PIDP: "Proportional/Integral/Derivative gain values for Pitch rate",
  PIDR: "Proportional/Integral/Derivative gain values for Roll rate",
  PIDS: "Proportional/Integral/Derivative gain values for ground steering yaw rate",
  PIDY: "Proportional/Integral/Derivative gain values for Yaw rate",
  PL: "Precision Landing messages",
  PM: "autopilot system performance and general data dumping ground",
  POS: "Canonical vehicle position",
  POWR: "System power information",
  PRTN: "Plane Parameter Tuning data",
  PRX: "Proximity Filtered sensor data",
  PRXR: "Proximity Raw sensor data",
  PSCD: "Position Control Down",
  PSCE: "Position Control East",
  PSCN: "Position Control North",
  PTUN: "Parameter Tuning information",
  RAD: "Telemetry radio statistics",
  RALY: "Rally point information",
  RATE: "Desired and achieved vehicle attitude rates. Not logged in Fixed Wing Plane modes.",
  RBCH: "Replay Data Beacon Header",
  RBCI: "Replay Data Beacon Instance",
  RBOH: "Replay body odometry data",
  RBRH: "Replay Data Barometer Header",
  RBRI: "Replay Data Barometer Instance",
  RCDA: "Raw RC data",
  RCI2: "(More) RC input channels to vehicle",
  RCIN: "RC input channels to vehicle",
  RCO2: "Servo channel output values 15 to 18",
  RCO3: "Servo channel output values 19 to 32",
  RCOU: "Servo channel output values 1 to 14",
  REPH: "Replay external position data",
  REV2: "Replay Event",
  REVH: "Replay external position data",
  REY3: "Replay Euler Yaw event",
  RFND: "Rangefinder sensor information",
  RGPH: "Replay Data GPS Header",
  RGPI: "Replay Data GPS Instance, infrequently changing data",
  RGPJ: "Replay Data GPS Instance - rapidly changing data",
  RMGH: "Replay Data Magnetometer Header",
  RMGI: "Replay Data Magnetometer Instance",
  ROFH: "Replay optical flow data",
  RPM: "Data from RPM sensors",
  RRNH: "Replay Data Rangefinder Header",
  RRNI: "Replay Data Rangefinder Instance",
  RSLL: "Replay Set Lat Lng event",
  RSO2: "Replay Set Origin event",
  RSSI: "Received Signal Strength Indicator for RC receiver",
  RVOH: "Replay Data Visual Odometry data",
  RWA2: "Replay set-default-airspeed event",
  RWOH: "Replay wheel odometry data",
  SA: "Simple Avoidance messages",
  SBPH: "Swift Health Data",
  SBRH: "Swift Raw Message Data",
  SCR: "Scripting runtime stats",
  SCVE: "Debug message for SCurve internal error",
  SIDD: "System ID data",
  SIDS: "System ID settings",
  SIM: "SITL simulator state",
  SIM2: "Additional simulator state",
  SITL: "Simulation data",
  SLV1: "Log data received from JSON simulator 1",
  SLV2: "Log data received from JSON simulator 2",
  SMOO: "Smoothed sensor data fed to EKF to avoid inconsistencies",
  SRTL: "SmartRTL statistics",
  STAK: "Stack information",
  TERR: "Terrain database information",
  THRO: "Throw Mode messages",
  THST: "Maximum thrust limitation based on battery voltage in Toy Mode",
  TRIG: "Camera shutter information",
  TRMP: "Torqeedo Motor Param",
  TRMS: "Torqeedo Motor Status",
  TRQD: "Torqeedo Status",
  TRSE: "Torqeedo System Setup",
  TRST: "Torqeedo System State",
  TSYN: "Time synchronisation response information",
  UBX1: "uBlox-specific GPS information (part 1)",
  UBX2: "uBlox-specific GPS information (part 2)",
  UBXT: "uBlox specific UBX-TIM-TM2 logging, see uBlox interface description",
  UNIT: "Message mapping from single character to SI unit",
  VER: "Ardupilot version",
  VIBE: "Processed (acceleration) vibration information",
  VISO: "Visual Odometry",
  VISP: "Vision Position",
  VISV: "Vision Velocity",
  VSTB: "Log message for video stabilisation software such as Gyroflow",
  WDOG: "Watchdog diagnostics",
  WENC: "Wheel encoder measurements",
  WINC: "Winch",
  WIND: "Windvane readings",
  XKF0: "EKF3 beacon sensor diagnostics",
  XKF1: "EKF3 estimator outputs",
  XKF2: "EKF3 estimator secondary outputs",
  XKF3: "EKF3 innovations",
  XKF4: "EKF3 variances. SV, SP, SH and SM are probably best described as 'Squared Innovation Test Ratios' where values <1 tells us the measurement was accepted and >1 tells us it was rejected.",
  XKF5: "EKF3 Sensor innovations (primary core) and general dumping ground",
  XKFD: "EKF3 Body Frame Odometry errors",
  XKFM: "EKF3 diagnostic data for on-ground-and-not-moving check",
  XKFS: "EKF3 sensor selection",
  XKQ: "EKF3 quaternion defining the rotation from NED to XYZ (autopilot) axes",
  XKT: "EKF3 timing information",
  XKTV: "EKF3 Yaw Estimator States",
  XKV1: "EKF3 State variances (primary core)",
  XKV2: "more EKF3 State Variances (primary core)",
  XKY0: "EKF Yaw Estimator States",
  XKY1: "EKF Yaw Estimator Innovation",
}

const mavlinkMessageDescriptions = {
  SYS_STATUS: "The general system state.",
  SYSTEM_TIME:
    "The system time is the time of the master clock, typically the computer clock of the main onboard computer.",
  GPS_RAW_INT:
    "The global position, as returned by the Global Positioning System (GPS). This is NOT the global position estimate of the system, but rather a RAW sensor value.",
  GPS_STATUS:
    "The positioning status, as reported by GPS. This message is intended to display status information about each satellite visible to the receiver.",
  SCALED_IMU:
    "The RAW IMU readings for the usual 9DOF sensor setup. This message should contain the scaled values to the described units",
  RAW_IMU:
    "The RAW IMU readings for a 9DOF sensor, which is identified by the id (default IMU1). This message should always contain the true raw values without any scaling to allow data capture and system debugging.",
  RAW_PRESSURE:
    "The RAW pressure readings for the typical setup of one absolute pressure and one differential pressure sensor. The sensor values should be the raw, UNSCALED ADC values.",
  SCALED_PRESSURE:
    "The pressure readings for the typical setup of one absolute and differential pressure sensor. The units are as specified in each field.",
  ATTITUDE:
    "The attitude in the aeronautical frame (right-handed, Z-down, Y-right, X-front, ZYX, intrinsic).",
  ATTITUDE_QUATERNION:
    "The attitude in the aeronautical frame (right-handed, Z-down, X-front, Y-right), expressed as quaternion. Quaternion order is w, x, y, z and a zero rotation would be expressed as (1 0 0 0).",
  LOCAL_POSITION_NED:
    "The filtered local position (e.g. fused computer vision and accelerometers). Coordinate frame is right-handed, Z-axis down (aeronautical frame, NED / north-east-down convention)",
  GLOBAL_POSITION_INT:
    "The filtered global position (e.g. fused GPS and accelerometers). The position is in GPS-frame (right-handed, Z-up). It is designed as scaled integer message since the resolution of float is not sufficient.",
  RC_CHANNELS_SCALED:
    "The scaled values of the RC channels received: (-100%) -10000, (0%) 0, (100%) 10000. Channels that are inactive should be set to INT16_MAX.",
  RC_CHANNELS_RAW:
    "The RAW values of the RC channels received. The standard PPM modulation is as follows: 1000 microseconds: 0%, 2000 microseconds: 100%. A value of UINT16_MAX implies the channel is unused. Individual receivers/transmitters might violate this specification.",
  SERVO_OUTPUT_RAW:
    "Superseded by ACTUATOR_OUTPUT_STATUS. The RAW values of the servo outputs (for RC input from the remote, use the RC_CHANNELS messages). The standard PPM modulation is as follows: 1000 microseconds: 0%, 2000 microseconds: 100%.",
  NAV_CONTROLLER_OUTPUT: "The state of the navigation and position controller.",
  RC_CHANNELS:
    "The PPM values of the RC channels received. The standard PPM modulation is as follows: 1000 microseconds: 0%, 2000 microseconds: 100%. A value of UINT16_MAX implies the channel is unused. Individual receivers/transmitters might violate this specification.",
  VFR_HUD: "Metrics typically displayed on a HUD for fixed wing aircraft.",
  RADIO_STATUS: "Status generated by radio and injected into MAVLink stream.",
  POWER_STATUS: "Power supply status.",
  DISTANCE_SENSOR: "Distance sensor information for an onboard rangefinder.",
  BATTERY_STATUS:
    "Battery information. Updates GCS with flight controller battery status.",
  VIBRATION: "Vibration levels and accelerometer clipping.",
}

export const logMessageDescriptions = {
  ...dataflashLogMessageDescriptions,
  ...mavlinkMessageDescriptions,
}
