from typing import Optional, Union

import pytest
from app import droneStatus, logger
from serial.serialutil import SerialException

from . import socketio_client


class FakeTCP:
    """
    Context manager that replaces master mavlink functions with ones that raise SerialException
    """

    @staticmethod
    def return_serial_exception(
        condition=None, type=None, blocking=False, timeout=None
    ) -> None:
        raise SerialException(
            "Test SerialException generated by tests.FakeTCP context manager."
        )

    def __enter__(self) -> None:
        if droneStatus.drone is not None:
            self.old_send = droneStatus.drone.master.mav.send
            droneStatus.drone.master.mav.send = FakeTCP.return_serial_exception

    def __exit__(self, type, value, traceback) -> None:
        if droneStatus.drone is not None:
            droneStatus.drone.master.mav.send = self.old_send


class NoDrone:
    """Context manager that sets the drone to `None` for the scope of the tests called within, then ensures the drone
    is returned to its previous state
    """

    def __enter__(self) -> None:
        if droneStatus.drone is None:
            logger.warning(
                "Calling NoDrone context manager when drone is already None."
            )
        self.oldDrone = droneStatus.drone
        droneStatus.drone = None

    def __exit__(self, type, value, traceback) -> None:
        droneStatus.drone = self.oldDrone


class ParamRefreshTimeout:
    """Context manager that replaces the mavlink recv_msg function in drone.master with a function that returns a False value
    and sets current_param_index to -1 to cause the refresh_params function to timeout with no params received from the drone
    """

    @staticmethod
    def returns_none(*args, **kwargs) -> None:
        return None

    def __enter__(self) -> None:
        if droneStatus.drone is not None:
            self.wait_for_message = droneStatus.drone.wait_for_message
            droneStatus.drone.wait_for_message = WaitForMessageReturnsNone.returns_none  # type: ignore[method-assign]
            self.old_param_index = (
                droneStatus.drone.paramsController.current_param_index
            )
            droneStatus.drone.paramsController.current_param_index = -1

    def __exit__(self, type, value, traceback) -> None:
        if droneStatus.drone is not None:
            droneStatus.drone.wait_for_message = self.wait_for_message  # type: ignore[method-assign]
            droneStatus.drone.paramsController.current_param_index = (
                self.old_param_index
            )


class WaitForMessageReturnsNone:
    @staticmethod
    def returns_none(*args, **kwargs) -> None:
        return None

    def __enter__(self) -> None:
        if droneStatus.drone is not None:
            self.wait_for_message = droneStatus.drone.wait_for_message
            droneStatus.drone.wait_for_message = WaitForMessageReturnsNone.returns_none  # type: ignore[method-assign]

    def __exit__(self, type, value, traceback) -> None:
        if droneStatus.drone is not None:
            droneStatus.drone.wait_for_message = self.wait_for_message  # type: ignore[method-assign]


class SetAircraftType:
    def __init__(self, aircraftType: int):
        self.aircraftType = aircraftType

    def __enter__(self) -> None:
        if droneStatus.drone is not None:
            self.old_aircraftType = droneStatus.drone.aircraft_type
            droneStatus.drone.aircraft_type = self.aircraftType

    def __exit__(self, type, value, traceback) -> None:
        if droneStatus.drone is not None:
            droneStatus.drone.aircraft_type = self.old_aircraftType


def send_and_recieve(endpoint: str, args: Optional[Union[dict, str]] = None) -> dict:
    """Sends a request to the socketio test client and returns the response

    Parameters
    ----------
    endpoint : str
        The endpoint to send the request to
    args : Optional[Union[dict, str]], optional
        The arguments to pass to the endpoint, by default None

    Returns
    -------
    dict
        The data recieved from the client
    """
    (
        socketio_client.emit(endpoint, args)
        if args is not None
        else socketio_client.emit(endpoint)
    )
    return socketio_client.get_received()[0]["args"][0]


@pytest.fixture
def gps_failure():
    """Fixture to use when you want the test being ran to simulate a GPS system failure.

    TODO: This does not work for some reason. Fix?
    """
    droneStatus.drone.logger.info("Enabling SIM_GPS_DISABLE")
    droneStatus.drone.master.param_set_send("SIM_GPS_DISABLE", 1.0, 2)
    droneStatus.drone.master.param_set_send("SIM_GPS2_DISABLE", 1.0, 2)

    yield

    droneStatus.drone.logger.info("Disabling SIM_GPS_DISABLE")
    droneStatus.drone.master.param_set_send("SIM_GPS_DISABLE", 0.0, 2)
    droneStatus.drone.master.param_set_send("SIM_GPS2_DISABLE", 0.0, 2)
