import time
from typing import List, Optional, Union

import pytest
from app import droneStatus, logger
from app.customTypes import Number
from serial.serialutil import SerialException

from . import socketio_client


class FakeTCP:
    """
    Context manager that replaces master mavlink functions with ones that raise SerialException
    """

    @staticmethod
    def return_serial_exception(*args, **kwargs) -> None:
        raise SerialException(
            "Test SerialException generated by tests.FakeTCP context manager."
        )

    def __enter__(self) -> None:
        if droneStatus.drone is not None:
            self.old_send = droneStatus.drone.master.mav.send
            droneStatus.drone.master.mav.send = FakeTCP.return_serial_exception

    def __exit__(self, type, value, traceback) -> None:
        if droneStatus.drone is not None:
            droneStatus.drone.master.mav.send = self.old_send


class NoDrone:
    """Context manager that sets the drone to `None` for the scope of the tests called within, then ensures the drone
    is returned to its previous state
    """

    def __enter__(self) -> None:
        if droneStatus.drone is None:
            logger.warning(
                "Calling NoDrone context manager when drone is already None."
            )
        self.oldDrone = droneStatus.drone
        droneStatus.drone = None

    def __exit__(self, type, value, traceback) -> None:
        droneStatus.drone = self.oldDrone


class ParamRefreshTimeout:
    """Context manager that replaces the mavlink recv_msg function in drone.master with a function that returns a False value
    and sets current_param_index to -1 to cause the refresh_params function to timeout with no params received from the drone
    """

    @staticmethod
    def returns_none(*args, **kwargs) -> None:
        return None

    def __enter__(self) -> None:
        if droneStatus.drone is not None:
            self.wait_for_message = droneStatus.drone.wait_for_message
            droneStatus.drone.wait_for_message = WaitForMessageReturnsNone.returns_none  # type: ignore[method-assign]
            self.old_param_index = (
                droneStatus.drone.paramsController.current_param_index
            )
            droneStatus.drone.paramsController.current_param_index = -1

    def __exit__(self, type, value, traceback) -> None:
        if droneStatus.drone is not None:
            droneStatus.drone.wait_for_message = self.wait_for_message  # type: ignore[method-assign]
            droneStatus.drone.paramsController.current_param_index = (
                self.old_param_index
            )


class WaitForMessageReturnsNone:
    @staticmethod
    def returns_none(*args, **kwargs) -> None:
        return None

    def __enter__(self) -> None:
        if droneStatus.drone is not None:
            self.wait_for_message = droneStatus.drone.wait_for_message
            droneStatus.drone.wait_for_message = WaitForMessageReturnsNone.returns_none  # type: ignore[method-assign]

    def __exit__(self, type, value, traceback) -> None:
        if droneStatus.drone is not None:
            droneStatus.drone.wait_for_message = self.wait_for_message  # type: ignore[method-assign]


def send_and_receive(endpoint: str, args: Optional[Union[dict, str]] = None) -> dict:
    """Sends a request to the socketio test client and returns the response

    Parameters
    ----------
    endpoint : str
        The endpoint to send the request to
    args : Optional[Union[dict, str]], optional
        The arguments to pass to the endpoint, by default None

    Returns
    -------
    dict
        The data received from the client
    """
    (
        socketio_client.emit(endpoint, args)
        if args is not None
        else socketio_client.emit(endpoint)
    )
    return socketio_client.get_received()[0]["args"][0]


@pytest.fixture
def gps_failure():
    """Fixture to use when you want the test being ran to simulate a GPS system failure.

    TODO: This does not work for some reason. Fix?
    """
    droneStatus.drone.logger.info("Enabling SIM_GPS_DISABLE")
    droneStatus.drone.master.param_set_send("SIM_GPS_DISABLE", 1.0, 2)
    droneStatus.drone.master.param_set_send("SIM_GPS2_DISABLE", 1.0, 2)

    yield

    droneStatus.drone.logger.info("Disabling SIM_GPS_DISABLE")
    droneStatus.drone.master.param_set_send("SIM_GPS_DISABLE", 0.0, 2)
    droneStatus.drone.master.param_set_send("SIM_GPS2_DISABLE", 0.0, 2)


def set_params(params: List[tuple[str, Number, int]]) -> None:
    """Sets multiple parameters on the drone with robust retry logic"""
    if droneStatus.drone is None:
        raise RuntimeError("No drone connected to set parameters on.")

    MAX_RETRIES = 7
    TIMEOUT = 2.0

    def drain_all():
        """Drain the entire buffer"""
        while True:
            msg = droneStatus.drone.master.recv_match(blocking=False)
            if msg is None:
                break

    pending = {name: (value, param_type) for name, value, param_type in params}
    retries = {name: 0 for name, _, _ in params}

    logger.debug(f"Setting {len(params)} params")

    drain_all()

    while pending:
        # Send all the pending params at once
        for param_name, (param_value, param_type) in pending.items():
            try:
                droneStatus.drone.master.mav.param_set_send(
                    droneStatus.drone.master.target_system,
                    droneStatus.drone.master.target_component,
                    param_name.encode("utf-8"),
                    param_value,
                    param_type,
                )
            except Exception:
                logger.warning(f"Error with set_send of param {param_name}")

        start_time = time.time()

        while time.time() - start_time < TIMEOUT and pending:
            try:
                msg = droneStatus.drone.master.recv_match(blocking=False)

                if msg is None:
                    time.sleep(0.005)
                    continue

                if msg.get_type() != "PARAM_VALUE":
                    continue

                param_name = msg.param_id

                if param_name in pending:
                    param_value, param_type = pending[param_name]
                    received_value = msg.param_value

                    if (
                        abs(received_value - param_value) < 0.001
                    ):  # Allow for floating point precision
                        logger.info(
                            f"Successfully set {param_name} to {param_value} (confirmed: {received_value})"
                        )

                        # Keep cached params coherent with direct MAVLink writes used in tests.
                        droneStatus.drone.paramsController.saveParam(
                            param_name,
                            received_value,
                            param_type,
                        )

                        pending.pop(param_name)

                    else:
                        logger.warning(
                            f"Parameter {param_name} was set but value mismatch: expected {param_value}, got {received_value}"
                        )
            except Exception:
                logger.warning(f"Error setting params, last param: {param_name}")

        # Retry only missing
        if pending:
            for param_name in list(pending.keys()):
                retries[param_name] += 1
                if retries[param_name] > MAX_RETRIES:
                    logger.error(
                        f"Failed to set {param_name} after {MAX_RETRIES} attempts"
                    )
                    raise RuntimeError(
                        f"Failed to set {param_name} after {MAX_RETRIES} attempts"
                    )

            logger.warning(f"Retrying: {list(pending.keys())}")

            drain_all()

    logger.info(f"Successfully set all {len(params)} parameters")
