name: Run Python Tests with simulator

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*

jobs:
  test:
    name: Python ${{ matrix.py }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        py:
          - 3.8
          - 3.9
          - 3.11
          - 3.12
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    services:
      service-name-1:
        image: kushmakkapati/ardupilot_sitl:latest
        ports:
          - 5760:5760
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.py }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}

      - name: Install dependencies
        working-directory: radio
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          python -m pip install -r requirements.txt

      - name: Test with pytest
        working-directory: radio
        run: pytest --log-cli-level=DEBUG
