name: Run Python Tests with simulator

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*

jobs:
  test-macos:
    name: Python ${{ matrix.py }} on macos-latest
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        py:
          - 3.8
          - 3.9
          - 3.11
          - 3.12
    steps:
      - uses: actions/checkout@v3

      - name: Set up docker
        run: |
          brew install --cask docker
          open /Applications/Docker.app
          while ! docker info >/dev/null 2>&1; do
            echo "Waiting for Docker to start..."
            sleep 2
          docker pull kushmakkapati/ardupilot_sitl
          docker run -it --rm -p 5760:5760 kushmakkapati/ardupilot_sitl

      - name: Set up Python ${{ matrix.py }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}

      - name: Install dependencies
        working-directory: radio
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          python -m pip install -r requirements.txt

      - name: Test with pytest
        working-directory: radio
        run: pytest --log-cli-level=DEBUG
  # test-linux:
  #   name: Python ${{ matrix.py }} on ubuntu-latest
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       py:
  #         - 3.8
  #         - 3.9
  #         - 3.11
  #         - 3.12
  #   services:
  #     service-name-1:
  #       image: kushmakkapati/ardupilot_sitl:latest
  #       ports:
  #         - 5760:5760
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Set up Python ${{ matrix.py }}
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: ${{ matrix.py }}

  #     - name: Install dependencies
  #       working-directory: radio
  #       run: |
  #         python -m pip install --upgrade pip
  #         python -m pip install pytest
  #         python -m pip install -r requirements.txt

  #     - name: Test with pytest
  #       working-directory: radio
  #       run: pytest --log-cli-level=DEBUG
